export enum SignupStatus {
    SIGNUP_CHOICE = 0,
    SIGNUP_CODE_STUDENT = 1,
    SIGNUP_FORM_STUDENT = 2,
    SIGNUP_FORM_TEACHER = 3,
    SIGNUP_EMAIL_CONFIRMATION = 4,
    SIGNUP_SUCCESS_STUDENT = 5,
    SIGNUP_SUCCESS_TEACHER = 6
  }